version: "3"

services:
  nginx:
    image: nginx:latest
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./log/nginx:/var/log/nginx
    ports:
      - 80:80
  db:
    image: postgres
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=finopolis
      - POSTGRES_PASSWORD=finopolis
  app:
    depends_on:
      - db
    image: application
    build:
      context: .
    entrypoint: bash -c 'while !</dev/tcp/db/5432; do sleep 3; done; uwsgi --ini uwsgi.ini'
    volumes:
      - ./:/home/appuser/app
      - ./log/app:/var/log/app
    ports:
      - 8080:5000
    environment:
      - FLASK_ENV=development
      - SETTINGS_FILE=../config.cfg
      - FLASK_APP=app.py
    dns:
      - 8.8.8.8
      - 4.4.4.4
  recreate-db:
    image: application
    depends_on:
      - db
    build:
      context: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 3; done; flask cli recreate-db'
    volumes:
      - ./:/home/appuser/app
      - ./log/app:/var/log/app
    environment:
      - FLASK_ENV=production
      - SETTINGS_FILE=../config.cfg
      - FLASK_APP=app.py